name: Run plugin-hrm-form CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create Temp Files
      run: |
        touch ./public/appConfig.js
        touch ./src/private/secret.js
    - name: Install Packages
      run: npm install
      working-directory: ./plugin-hrm-form
    - name: Run Lint
      run: npm run lint --if-present
      working-directory: ./plugin-hrm-form
    - name: Run Tests
      run: npm test
      working-directory: ./plugin-hrm-form
      env:
        CI: true
