name: Run plugin-hrm-form CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Go to plugin-hrm-form folder
      run: cd plugin-hrm-form
    - name: Install Packages
      run: npm install
    - name: Run Lint
      run: npm run lint --if-present
    - name: Run Tests
      run: npm test
      env:
        CI: true
